### ISSUE TITLE
non-const global variable

### ISSUE THREAD

**Issue by Moelf** [serenity4/Swizzles.jl#1]
https://github.com/serenity4/Swizzles.jl/blob/83b0e48369d3c9eee295bfde79e1c95f5fc28d61/src/Swizzles.jl#L64-L82

should these be `const`? Also maybe `Dict` should be `NamedTuple` for faster access?

**Comment by serenity4** [comment]
Whoops, I forgot to make it `const` after prototyping, thanks.

I would say that `Dict` is fine, this dictionary will only be accessed during macro expansion time, so nothing runtime-critical. As a very minor advantage, I believe `Dict` would require less compilation.

**Comment by serenity4** [comment]
Fixed in https://github.com/serenity4/Swizzles.jl/commit/72b79492077319ced01733bdad88d1b452c3ccc9

**Comment by Moelf** [comment]
https://github.com/serenity4/Swizzles.jl/blob/72b79492077319ced01733bdad88d1b452c3ccc9/src/Swizzles.jl#L78-L82

does this not need to be `const` as well?

**Comment by serenity4** [comment]
ad4bb76
