### ISSUE TITLE
`@swizzle_` example is broken

### ISSUE THREAD

**Issue by c42f** [serenity4/Swizzles.jl#2]
This is a lovely little package, thanks for making it :heart:

I was curious about the implementation and the use of `ScopedValue` also caught my eye as a kind of "uhoh using dynamic scope for this looks like a possibly dubious idea" :sweat_smile: 

The implementation of `@swizzle_` looks broken:

```julia
julia> macro _swizzle(ex)
         new_names = Dict('w' => 1, 'h' => 2, 'd' => 3)
         ex = quote
           @with Swizzles.component_names => merge(Swizzles.component_names[], $new_names) do
             # One might also pass around a `T` parameter as second argument.
             Swizzles.generate_swizzle_expr($ex)
           end
         end
         esc(ex)
       end
@_swizzle (macro with 1 method)

julia> @_swizzle [1,2].hd
ERROR: MethodError: no method matching (::var"#23#24")(::Int64, ::Int64)
Stacktrace:
 [1] mergewith!(combine::var"#23#24", d1::Dict{Char, Int64}, d2::Dict{Char, Int64})
   @ Base ./dict.jl:782
 [2] merge!(::Function, ::Dict{Char, Int64}, ::Dict{Char, Int64})
   @ Base ./abstractdict.jl:291
 [3] merge(combine::Function, d::Dict{Char, Int64}, others::Dict{Char, Int64})
   @ Base ./abstractdict.jl:400
 [4] macro expansion
   @ scopedvalues.jl:195 [inlined]
 [5] top-level scope
   @ REPL[75]:4
```

But actually you don't need it because `@swizzle` itself is already fully customizable using `@with` - but you need to do it at macro expansion time:

```julia
julia> @with Swizzles.component_names => merge(Swizzles.component_names[], Dict('w' => 1, 'h' => 2, 'd' => 3)) begin
           @macroexpand @swizzle [1,2].hd
       end
:((Swizzles.swizzle)([1, 2], 2, 3))

julia> @macroexpand @swizzle [1,2].hd
ERROR: KeyError: key 'h' not found
Stacktrace:
 [1] getindex(h::Dict{Char, Int64}, key::Char)
   @ Base ./dict.jl:510
 [2] _generate_swizzle_expr(ex::Expr, T::Nothing)
   @ Swizzles ~/.julia/dev/Swizzles/src/Swizzles.jl:103
[...]
```

With this in mind, you can customize the behavior of `@swizzle` within a file by doing something like

```julia
@with Swizzles.component_names => merge(Swizzles.component_names[], Dict('w' => 1, 'h' => 2, 'd' => 3)) begin
    include("my_swizzles.jl")

    # or the following should also work
    @eval begin
        @swizzle [1,2].hd
    end
end
```

Where my_swizzles.jl can include `w`, `h` and `d` as fields.

**Comment by c42f** [comment]
Overall I'm quite surprised by this use of `ScopedValue` ... but I think in a very good way: Use of *dynamic* scope at macro expansion time provides *lexical* scope customizations for macros. And lexical scope is what you want for syntax.

My mind is kind of blown by this and I love it and I might use it one day.

**Comment by serenity4** [comment]
Very good observations! The `@_swizzle` example in the docs was broken, but a corresponding implementation in the test suite did work. I forgot to update the corresponding docs afterwards :facepalm: the trick is that the code that generates the expression must be evaluated straight away in the macro logic, and not be deferred to further expansion.

The motivation for a `@_swizzle` macro was that one could then avoid having to make sure there is proper scoping for an expression to work. As in, I code in `file.jl` using `@swizzle [1, 2].h`, and then including this file may or may not work depending on dynamic scope - which in this case would likely be determined by lexical scope as you point out. Although for that purpose, scoped values are overkill and a function parameter could have achieved the same thing.

I made a few updates in https://github.com/serenity4/Swizzles.jl/commit/d58c1fabd0ba47ae3fa0252f1d5771a6d7fb2212, hopefully that makes things clearer. I also added a note about the uses you described with `include` and `@eval begin ... end`, as an alternative to reimplementing a macro such as `@_swizzle` if one is OK relying on lexical scoping.

**Comment by c42f** [comment]
Nice, sounds good!

I think for the use of package authors the lexical scope version makes most sense and is super easy to use. This is what I was thinking about when I wrote the comments above.

On the other hand wrapping an entire script in `@eval` is ugly and it's not a good solution for one-off scripts.

So I can see a case for both uses.
